name: Deployment to dev.osmgo.com

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Create build
        run: npm run build

      - name: rsync deployments
        if: success()
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: www/
          remote_path: ${{ secrets.DEV_OSMGO_DEPLOY_PATH }}
          remote_host: osmgo.com
          remote_port: 22
          remote_user: ${{ secrets.OSMGO_SRV_USER }}
          remote_key: ${{ secrets.OSMGO_SRV_KEY }}
